<?php
/**
 * @file
 * tn_widget_tweaks.module - UI and behaviour alterations for Widgetizer module.
 *
 * By Jim Kirkpatrick - i-jk.co.uk
 *
 * Sponsored by Transition Network - transitionnetwork.org
 *
 * LICENCE
 *
 * DESCRIPTION
 */

/**
 * Implements hook_custom_theme().
 */
function tn_widget_tweaks_custom_theme() {
  // Ensure all /tn-widgets/* pages use the appropriate theme.
  if (arg(0) == 'tn-widgets') {
    // Hide admin nmenu if present, too.
    if (module_exists('admin_menu')) {
      admin_menu_suppress();
    }
    // Set our theme.
    return 'tn_widget_tweaks_theme';
  }
}

function tn_widget_tweaks_form_alter(&$form, &$form_state, $form_id) {
  // Only act if this is a workflow-enabled form.
  //if ($form)
}
